spring.profiles.active=dev

spring.config.import=classpath:custom-config.properties

# Server port (default to 8080 if PORT is not set)
server.port=${PORT:8080}

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Disable open-in-view to avoid lazy loading issues
spring.jpa.open-in-view=false